# Generated by Django 5.1.6 on 2025-02-06 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='answerweight',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.characteristic'),
        ),
    ]
