# Generated by Django 5.1.6 on 2025-04-16 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_characteristic_alter_answerweight_trait'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PsychologicalPortrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendations', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepresentationalSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Temperament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperament_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PsychProfileTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait_name', models.CharField(max_length=255)),
                ('trait_value', models.CharField(max_length=255)),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='core.psychologicalportrait')),
            ],
        ),
        migrations.AddField(
            model_name='psychologicalportrait',
            name='representational_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portraits', to='core.representationalsystem'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.group')),
            ],
        ),
        migrations.AddField(
            model_name='psychologicalportrait',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psychological_portrait', to='core.student'),
        ),
        migrations.CreateModel(
            name='LearningRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_text', models.TextField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_recommendation', to='core.student')),
            ],
        ),
        migrations.AddField(
            model_name='psychologicalportrait',
            name='temperament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portraits', to='core.temperament'),
        ),
    ]
