# Generated by Django 5.1.6 on 2025-04-18 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerweight',
            name='answer',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='core.answer'),
            preserve_default=False,
        ),
    ]
